### ISSUE TITLE
Question : Labelling Thanos receivers  statefulset

### ISSUE THREAD

**Issue by Adaendra** [observatorium/thanos-receive-controller#90]
In the [README](https://github.com/observatorium/thanos-receive-controller), it's said at the end :

> Finally, deploy StatefulSets of Thanos receivers labeled with controller.receive.thanos.io=thanos-receive-controller. 

Does the value of the label `controller.receive.thanos.io` is `thanos-receive-controller` because it's hardcoded somewhere ? 
Or is it because it's the name of the Deployment which is declared before in the documentation ?

*Extract of the Deployment declaration*
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: thanos-receive-controller
```

Thanks for your help
